version: '3.8'

services:
  kyc-backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      - ./logs:/app/logs
    command: python app/web_interface.py backend
    depends_on:
      - redis

  kyc-frontend:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - kyc-backend
    environment:
      - BACKEND_URL=http://kyc-backend:8000
    command: streamlit run app/web_interface.py --server.port=8501 --server.address=0.0.0.0

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: